# Generated by Django 2.2.13 on 2023-05-05 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20230501_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video', models.TextField()),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='login',
            name='Mobile_Number',
            field=models.CharField(max_length=13),
        ),
    ]
