# Generated by Django 2.2.13 on 2023-05-05 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20230505_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='forest_officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='report_intrusion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Animal', models.TextField()),
                ('Location', models.TextField()),
                ('Date_and_Time', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='login',
            name='Mobile_Number',
            field=models.IntegerField(),
        ),
    ]
