# Generated by Django 2.2.13 on 2023-05-05 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20230505_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='Mobile_Number',
            field=models.TextField(max_length=13),
        ),
    ]
