# Generated by Django 2.2.13 on 2023-05-06 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_addcameralocation_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='addcameraLocation',
            new_name='add_camera_Location',
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
