# Generated by Django 2.2.13 on 2023-05-06 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20230506_1629'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='camera',
            new_name='app1_camera',
        ),
    ]
