# Generated by Django 2.2.13 on 2023-05-06 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20230506_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video', models.TextField()),
                ('Latitude', models.FloatField()),
                ('Longitude', models.FloatField()),
                ('Location', models.TextField()),
                ('Animal', models.TextField()),
                ('Datetime', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='app1_camera',
        ),
    ]
