# Generated by Django 2.2.13 on 2023-05-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20230506_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='suggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Designation', models.TextField()),
                ('Email', models.TextField()),
                ('suggestions', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='forest_officer',
        ),
    ]
