# Generated by Django 2.2.13 on 2023-05-07 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20230507_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camera',
            name='Location',
        ),
    ]
