# Generated by Django 4.0.5 on 2023-05-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_remove_camera_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_camera_location',
            name='Video',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='Latitude',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='Longitude',
        ),
        migrations.RemoveField(
            model_name='camera',
            name='Video',
        ),
        migrations.AddField(
            model_name='add_camera_location',
            name='CAM_ID',
            field=models.TextField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add_camera_location',
            name='Location',
            field=models.TextField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camera',
            name='CAM_ID',
            field=models.TextField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='camera',
            name='Animal',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='camera',
            name='Datetime',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='forest_department_login',
            name='Designation',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='forest_department_login',
            name='Division',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='forest_department_login',
            name='Name',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='report_intrusion',
            name='Animal',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='report_intrusion',
            name='Date_and_Time',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='report_intrusion',
            name='Location',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='suggestions',
            name='Designation',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='suggestions',
            name='Email',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='suggestions',
            name='Name',
            field=models.TextField(max_length=30),
        ),
        migrations.AlterField(
            model_name='suggestions',
            name='suggestions',
            field=models.TextField(max_length=500),
        ),
    ]
